/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./components/common/BottomBar.vue')['default']
    InnerNavBar: typeof import('./components/common/InnerNavBar.vue')['default']
    OuterFooter: typeof import('./components/common/outerFooters/OuterFooter.vue')['default']
    OuterFooter2: typeof import('./components/common/outerFooters/OuterFooter2.vue')['default']
    OuterNavbar1: typeof import('./components/common/outerNavbars/OuterNavbar1.vue')['default']
    OuterNavbar2: typeof import('./components/common/outerNavbars/OuterNavbar2.vue')['default']
    OuterNavbar3: typeof import('./components/common/outerNavbars/OuterNavbar3.vue')['default']
    OuterNavbar4: typeof import('./components/common/outerNavbars/OuterNavbar4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
