/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutUsView': RouteRecordInfo<'/AboutUsView', '/AboutUsView', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/AnnouncementsView': RouteRecordInfo<'/admin/AnnouncementsView', '/admin/AnnouncementsView', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementCreateEditDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementCreateEditDialog', '/admin/dialogs/AnnouncementCreateEditDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDeleteConfirmationDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDeleteConfirmationDialog', '/admin/dialogs/AnnouncementDeleteConfirmationDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AnnouncementDetailDialog': RouteRecordInfo<'/admin/dialogs/AnnouncementDetailDialog', '/admin/dialogs/AnnouncementDetailDialog', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/hometab/HomeAnnouncements': RouteRecordInfo<'/hometab/HomeAnnouncements', '/hometab/HomeAnnouncements', Record<never, never>, Record<never, never>>,
    '/hometab/HomeLogs': RouteRecordInfo<'/hometab/HomeLogs', '/hometab/HomeLogs', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/otherTab/Page1View': RouteRecordInfo<'/otherTab/Page1View', '/otherTab/Page1View', Record<never, never>, Record<never, never>>,
    '/PortfolioView': RouteRecordInfo<'/PortfolioView', '/PortfolioView', Record<never, never>, Record<never, never>>,
    '/VisionMissionView': RouteRecordInfo<'/VisionMissionView', '/VisionMissionView', Record<never, never>, Record<never, never>>,
  }
}
